In [1]:
import pandas as pd
A = pd.read_csv("C:/Users/akaks/Downloads/Credit.csv")

In [2]:
A.head()

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331

In [3]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  400 non-null    int64
 1   ID          400 non-null    int64
 2   Income      400 non-null    float64
 3   Limit       400 non-null    int64
 4   Rating      400 non-null    int64
 5   Cards       400 non-null    int64
 6   Age         400 non-null    int64
 7   Education   400 non-null    int64
 8   Gender      400 non-null    object
 9   Student     400 non-null    object
 10  Married     400 non-null    object
 11  Ethnicity   400 non-null    object
 12  Balance     400 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 40.8+ KB

# Dropping Unwanted columns

In [4]:
X = A.drop(labels=['Unnamed: 0','ID','Student'],axis=1)

In [10]:
Y = A[['Student']]

In [11]:
X

,Income,Limit,Rating,Cards,Age,Education,Gender,Married,Ethnicity,Balance
0,14.891,3606,283,2,34,11,Male,Yes,Caucasian,333
1,106.025,6645,483,3,82,15,Female,Yes,Asian,903
2,104.593,7075,514,4,71,11,Male,No,Asian,580
3,148.924,9504,681,3,36,11,Female,No,Asian,964
4,55.882,4897,357,2,68,16,Male,Yes,Caucasian,331
...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,Male,Yes,Caucasian,560
396,13.364,3838,296,5,65,17,Male,No,African American,480
397,57.872,4171,321,5,67,12,Female,Yes,Caucasian,138
398,37.728,2525,192,1,44,13,Male,Yes,Caucasian,0
399,18.701,5524,415,5,64,7,Female,No,Asian,966

# Preparing Y column

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Ynew = le.fit_transform(Y)

C:\Users\akaks\anaconda3\envs\Deep_Learning\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [14]:
#Ynew

# Preprocessing

In [16]:
cat = []
con = []
for i in X.columns:
    if X[i].dtype=="O":
        cat.append(i)
    else:
        con.append(i)
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X1 = pd.DataFrame(ss.fit_transform(X[con]),columns=con)

In [18]:
X2 = pd.get_dummies(X[cat])

In [20]:
Xnew = X1.join(X2)

In [21]:
Xnew

,Income,Limit,Rating,Cards,Age,Education,Balance,Gender_ Male,Gender_Female,Married_No,Married_Yes,Ethnicity_African American,Ethnicity_Asian,Ethnicity_Caucasian
0,-0.861583,-0.489999,-0.465539,-0.699130,-1.257674,-0.784930,-0.407277,1,0,0,1,0,0,1
1,1.727437,0.828261,0.828703,0.031032,1.528451,0.496588,0.834056,0,1,0,1,0,1,0
2,1.686756,1.014787,1.029311,0.761194,0.889964,-0.784930,0.130634,1,0,1,0,0,1,0
3,2.946152,2.068440,2.110003,0.031032,-1.141586,-0.784930,0.966900,0,1,1,0,0,1,0
4,0.302928,0.070012,0.013331,-0.699130,0.715831,0.816968,-0.411633,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,-0.940986,-0.275711,-0.310230,0.031032,-1.373763,-0.144171,0.087078,1,0,0,1,0,0,1
396,-0.904963,-0.389362,-0.381413,1.491355,0.541698,1.137347,-0.087144,1,0,1,0,1,0,0
397,0.359462,-0.244913,-0.219633,1.491355,0.657787,-0.464550,-0.831944,0,1,0,1,0,0,1
398,-0.212808,-0.958916,-1.054419,-1.429291,-0.677231,-0.144171,-1.132477,1,0,0,1,0,0,1
399,-0.753345,0.341993,0.388661,1.491355,0.483654,-2.066448,0.971256,0,1,1,0,0,1,0

In [22]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Ynew,test_size=0.2,random_state=21)

In [23]:
Xnew.shape

(400, 14)

# Create a NN

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [39]:
#In output layer we will use activatin function as sigmoid

In [25]:
nn = Sequential()
nn.add(Dense(14,input_dim=14))
nn.add(Dense(10))
nn.add(Dense(1,activation='sigmoid'))

# Training the NN

In [28]:
nn.compile(loss = 'binary_crossentropy',metrics='accuracy')
nn.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1226 - accuracy: 0.9563
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1146 - accuracy: 0.9594
Epoch 3/100
10/10 [==============================] - 0s 1ms/step - loss: 0.1092 - accuracy: 0.9594
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.1054 - accuracy: 0.9625
Epoch 5/100
10/10 [==============================] - 0s 1ms/step - loss: 0.1014 - accuracy: 0.9656
Epoch 6/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0978 - accuracy: 0.9625
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0943 - accuracy: 0.9656
Epoch 8/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0905 - accuracy: 0.9719
Epoch 9/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0874 - accuracy: 0.9750
Epoch 10/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0850 - accuracy: 0.9719
Epoch 11/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0811 - accuracy: 0.9750
Epoch 12/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0796 - accuracy: 0.9719
Epoch 13/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0756 - accuracy: 0.9750
Epoch 14/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0732 - accuracy: 0.9781
Epoch 15/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0712 - accuracy: 0.9750
Epoch 16/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0692 - accuracy: 0.9781
Epoch 17/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0668 - accuracy: 0.9812
Epoch 18/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0648 - accuracy: 0.9812
Epoch 19/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0641 - accuracy: 0.9812
Epoch 20/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0613 - accuracy: 0.9812
Epoch 21/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0590 - accuracy: 0.9812
Epoch 22/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0594 - accuracy: 0.9844
Epoch 23/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0565 - accuracy: 0.9812
Epoch 24/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0554 - accuracy: 0.9812
Epoch 25/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9812
Epoch 26/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0522 - accuracy: 0.9812
Epoch 27/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0515 - accuracy: 0.9812
Epoch 28/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0508 - accuracy: 0.9812
Epoch 29/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9844
Epoch 30/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0493 - accuracy: 0.9844
Epoch 31/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0470 - accuracy: 0.9844
Epoch 32/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0459 - accuracy: 0.9875
Epoch 33/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0461 - accuracy: 0.9875
Epoch 34/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0445 - accuracy: 0.9844
Epoch 35/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0447 - accuracy: 0.9875
Epoch 36/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0435 - accuracy: 0.9844
Epoch 37/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0432 - accuracy: 0.9875
Epoch 38/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0419 - accuracy: 0.9906
Epoch 39/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0416 - accuracy: 0.9906
Epoch 40/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0403 - accuracy: 0.9937
Epoch 41/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0407 - accuracy: 0.9906
Epoch 42/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0391 - accuracy: 0.9906
Epoch 43/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0393 - accuracy: 0.9937
Epoch 44/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0387 - accuracy: 0.9906
Epoch 45/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0378 - accuracy: 0.9906
Epoch 46/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0384 - accuracy: 0.9875
Epoch 47/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0374 - accuracy: 0.9906
Epoch 48/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0378 - accuracy: 0.9906
Epoch 49/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0372 - accuracy: 0.9906
Epoch 50/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 0.9906
Epoch 51/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0358 - accuracy: 0.9875
Epoch 52/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0347 - accuracy: 0.9937
Epoch 53/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0360 - accuracy: 0.9906
Epoch 54/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0336 - accuracy: 0.9875
Epoch 55/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0346 - accuracy: 0.9875
Epoch 56/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0337 - accuracy: 0.9937
Epoch 57/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0351 - accuracy: 0.9906
Epoch 58/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0342 - accuracy: 0.9906
Epoch 59/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0343 - accuracy: 0.9906
Epoch 60/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0325 - accuracy: 0.9937
Epoch 61/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0322 - accuracy: 0.9937
Epoch 62/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0324 - accuracy: 0.9875
Epoch 63/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0322 - accuracy: 0.9937
Epoch 64/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0311 - accuracy: 0.9906
Epoch 65/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0318 - accuracy: 0.9906
Epoch 66/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0310 - accuracy: 0.9937
Epoch 67/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0327 - accuracy: 0.9906
Epoch 68/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0333 - accuracy: 0.9906
Epoch 69/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0304 - accuracy: 0.9937
Epoch 70/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0296 - accuracy: 0.9937
Epoch 71/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0311 - accuracy: 0.9906
Epoch 72/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0298 - accuracy: 0.9906
Epoch 73/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0308 - accuracy: 0.9937
Epoch 74/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0310 - accuracy: 0.9937
Epoch 75/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0296 - accuracy: 0.9937
Epoch 76/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0301 - accuracy: 0.9906
Epoch 77/100
10/10 [==============================] - 0s 997us/step - loss: 0.0298 - accuracy: 0.9906
Epoch 78/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0302 - accuracy: 0.9844
Epoch 79/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0300 - accuracy: 0.9906
Epoch 80/100
10/10 [==============================] - 0s 2ms/step - loss: 0.0293 - accuracy: 0.9906
Epoch 81/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0287 - accuracy: 0.9906
Epoch 82/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0306 - accuracy: 0.9937
Epoch 83/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0276 - accuracy: 0.9906
Epoch 84/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0288 - accuracy: 0.9906
Epoch 85/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0302 - accuracy: 0.9906
Epoch 86/100
10/10 [==============================] - 0s 997us/step - loss: 0.0278 - accuracy: 0.9937
Epoch 87/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0281 - accuracy: 0.9937
Epoch 88/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0276 - accuracy: 0.9875
Epoch 89/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0283 - accuracy: 0.9906
Epoch 90/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0278 - accuracy: 0.9937
Epoch 91/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0281 - accuracy: 0.9875
Epoch 92/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0271 - accuracy: 0.9937
Epoch 93/100
10/10 [==============================] - 0s 997us/step - loss: 0.0281 - accuracy: 0.9906
Epoch 94/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0265 - accuracy: 0.9937
Epoch 95/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0278 - accuracy: 0.9906
Epoch 96/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0293 - accuracy: 0.9906
Epoch 97/100
10/10 [==============================] - 0s 997us/step - loss: 0.0260 - accuracy: 0.9937
Epoch 98/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0261 - accuracy: 0.9937
Epoch 99/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0277 - accuracy: 0.9937
Epoch 100/100
10/10 [==============================] - 0s 1ms/step - loss: 0.0281 - accuracy: 0.9844

# Training accuracy

In [30]:
Q = []
for i in nn.predict(xtrain):
    if(i<0.5):
        Q.append(0)
    else:
        Q.append(1)

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(ytrain,Q)

0.99375

In [34]:
confusion_matrix(ytrain,Q)

array([[286,   1],
       [  1,  32]], dtype=int64)

# Testing Accuracy

In [35]:
Q = []
for i in nn.predict(xtest):
    if(i<0.5):
        Q.append(0)
    else:
        Q.append(1)

In [36]:
confusion_matrix(ytest,Q)

array([[73,  0],
       [ 1,  6]], dtype=int64)

In [37]:
accuracy_score(ytest,Q)

0.9875